language: node_js
node_js: 8

install:
  - npm install

script:
  - npx nps test.coverage
  - npx nps build

after_success:
  - npx codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
